pages_repos:
  - repo: datascients-guide
    url: https://alex-des-santos.github.io/datascients-guide/
    title: "Data Science Guide"
    description: "Guia completo de Data Science"
  - repo: csv-insights-tool
    url: https://alex-des-santos.github.io/csv-insights-tool/
    title: "CSV Insights Tool"
    description: "Ferramenta para análise de arquivos CSV"
  # Adicione novos repos com GitHub Pages aqui
  - repo: analise-habitos-desempenho-do-repo
    url: https://alex-des-santos.github.io/analise-habitos-desempenho/
    title: "Análise Interativa de Hábitos Estudantis e Desempenho Acadêmico"
    description: "Análise de Hábitos e Desempenho de estudantes do Kaggle"
  - repo: resume-otimizator
    url: https://github.com/alex-des-santos/resume-otimizator
    title: "Assistente de Carreira com IA – Otimizador de Currículo"
    description: "Otimize seu currículo, prepare-se para entrevistas e fortaleça sua presença profissional usando inteligência artificial generativa."  
  # Adicione novos repos com GitHub Pages aqui
  # - repo: nome-do-repo
  #   url: https://alex-des-santos.github.io/nome-do-repo/
  #   title: "Título do Projeto"
  #   description: "Descrição breve do projeto"
